language: rust
dist: xenial
sudo: required
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - env: NAME='cargo-travis'
  include:
  - rust: beta
    before_install:
    - sudo apt-get update
    - sudo apt-get install -y qemu-user
    before_script:
      - rustup target add thumbv6m-none-eabi thumbv7m-none-eabi thumbv7em-none-eabi thumbv7em-none-eabihf
      - cargo install cargo-binutils
      - rustup component add llvm-tools-preview
      - cd tests/qemu-arm-cortex-m
    script:
      - ./build-deploy-all.bash