[package]
name = "rudie"
version = "0.1.0"
authors = ["Peter LeVasseur <plevasseur@gmail.com>"]

[dependencies]
typenum = "1.10.0"
generic-array = "0.11.0"

nalgebra = { version = "0.15", default-features = false }